# Generated by Django 2.0.6 on 2019-09-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksOnTheTable2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=20, null=True)),
                ('the_author', models.CharField(blank=True, max_length=20, null=True)),
                ('pricing', models.CharField(blank=True, max_length=20, null=True)),
                ('dna_dan_jia', models.CharField(blank=True, max_length=20, null=True)),
                ('version_of_the_club', models.CharField(blank=True, max_length=20, null=True)),
                ('edition', models.CharField(blank=True, max_length=20, null=True)),
                ('impression', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_words', models.CharField(blank=True, max_length=20, null=True)),
                ('number_of_pages', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('the_paper', models.CharField(blank=True, max_length=20, null=True)),
                ('packaging', models.CharField(blank=True, max_length=20, null=True)),
                ('printing_time', models.CharField(blank=True, max_length=20, null=True)),
                ('the_editors_recommend', models.TextField(blank=True, null=True)),
                ('plot_summary', models.TextField(blank=True, null=True)),
                ('about_the_author', models.TextField(blank=True, null=True)),
                ('catalogue', models.TextField(blank=True, null=True)),
                ('meddia_comments', models.TextField(blank=True, null=True)),
                ('highlights_illustrations', models.CharField(blank=True, max_length=100, null=True)),
                ('whether_suit', models.CharField(blank=True, max_length=20, null=True)),
                ('trying_to_read_online', models.TextField(blank=True, null=True)),
                ('classify', models.CharField(blank=True, max_length=20, null=True)),
                ('isbn_id', models.IntegerField(db_column='ISBN_id')),
                ('bei_4', models.CharField(blank=True, max_length=10, null=True)),
                ('bei_5', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'books_on_the_table2',
            },
        ),
        migrations.CreateModel(
            name='County2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('county_county', models.CharField(blank=True, max_length=20, null=True)),
                ('province_id', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'county2',
            },
        ),
        migrations.CreateModel(
            name='InTheClassification',
            fields=[
                ('taxon', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('taxon_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'in_the_classification',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_id', models.CharField(blank=True, max_length=20, null=True)),
                ('order_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('order_time', models.CharField(blank=True, max_length=20, null=True)),
                ('order_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'order_list',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_city', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'province',
            },
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isbn_id', models.CharField(blank=True, db_column='ISBN_id', max_length=20, null=True)),
                ('id_id', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.CharField(max_length=20)),
                ('book_id', models.CharField(max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'shopping',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('consignee', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=20, null=True)),
                ('detailed_address', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('cell_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('user_id', models.CharField(max_length=20)),
                ('column_8', models.CharField(db_column='Column_8', max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='TheOrderContent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_list_id', models.CharField(max_length=20)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('books_on_the_table2', models.CharField(max_length=20)),
                ('isbn_id', models.CharField(db_column='ISBN_id', max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'the_order_content',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('town_town', models.CharField(blank=True, max_length=20, null=True)),
                ('village_id', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'town',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pow', models.CharField(blank=True, max_length=200, null=True)),
                ('id_id', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=200)),
            ],
            options={
                'managed': False,
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('village_village', models.CharField(blank=True, max_length=20, null=True)),
                ('county_id', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'village',
            },
        ),
    ]
